### ISSUE TITLE
BetaPilot 4.3.7

### ISSUE THREAD

**Issue by Luix333** [olliw42/ardupilot#3]
Hi, first of all I want to thank you for your great work!

I'd like to know if there's in any plans of compiling BetaCopter 4.3.7? Or if there is any tutorials/instructions out there on how to do it (I don't have any experience compiling).  Or maybe even plans for merging this into Ardupilot?

Thanks again for your amazing work!

**Comment by olliw42** [comment]
you can follow any ArduPilot tutorial for compiling. There is nothing special with BetaPilot, it's just a branch.
